language: c

before_install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs mono-complete > /dev/null
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true
  - cd TestWebApp/
  - wget http://nuget.org/nuget.exe
  - mono --runtime=v4.0 nuget.exe restore

script:
  - xbuild TestWebApp.sln
