language: c

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true
  - cd TestWebApp/
  - wget http://nuget.org/nuget.exe
  - mono --runtime=v4.5 nuget.exe restore

script:
  - xbuild TestWebApp.sln
