language: c

before_install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get install mono-devel mono-mcs nunit-console
  - mozroots --import --sync
  - mono --version
  - export EnableNuGetPackageRestore=true
  - cd TestWebApp/
  - wget http://nuget.org/nuget.exe
  - 

script:
  - mono --runtime=v4.5 nuget.exe restore
  - xbuild TestWebApp.sln
