language: c

before_install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get install mono-devel mono-mcs nunit-console
  - mozroots --import --sync
  - mono --version
  - wget -P TestWebApp http://nuget.org/nuget.exe



script:
  - cd TestWebApp/
  - mono --runtime=v4.0 nuget.exe restore
  - xbuild TestWebApp.sln
